version: "3"
services:
  app: 
    build: .
    command: npm start
    ports:
     - "3000:3000"
    volumes:
      - .:/usr/app
  db:
    container_name: projectJr
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: p4ssw0rd1234